### ISSUE TITLE
SocketProtocolError : Socket hung up while trying to setup socketcluster locally following SCC Guide

### ISSUE THREAD

**Issue by nagamanojv** [SocketCluster/socketcluster#293]
I was able to successfully run single instance of Socketcluster app for the past one week. Now I am trying to setup multiple instances of socketclusters to handle huge load. I am following the SCC guide to setup the cluster locally. The state server and broker runs without any issue but when I try to run socketcluster app pointing to state server, it fails with the following exception.

`{ Error
    at SCSocket._onSCClose (/mnt/ebs/deploy/SCCluster/socketcluster/sample/node_modules/socketcluster-client/lib/scsocket.js:597:15)
    at SCTransport.<anonymous> (/mnt/ebs/deploy/SCCluster/socketcluster/sample/node_modules/socketcluster-client/lib/scsocket.js:290:12)
    at SCTransport.Emitter.emit (/mnt/ebs/deploy/SCCluster/socketcluster/sample/node_modules/component-emitter/index.js:131:20)
    at SCTransport.SCEmitter.emit (/mnt/ebs/deploy/SCCluster/socketcluster/sample/node_modules/sc-emitter/index.js:40:26)
    at SCTransport._onClose (/mnt/ebs/deploy/SCCluster/socketcluster/sample/node_modules/socketcluster-client/lib/sctransport.js:175:30)
    at WebSocket.wsSocket.onerror (/mnt/ebs/deploy/SCCluster/socketcluster/sample/node_modules/socketcluster-client/lib/sctransport.js:104:12)
    at WebSocket.onError (/mnt/ebs/deploy/SCCluster/socketcluster/sample/node_modules/ws/lib/WebSocket.js:452:14)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.EventEmitter.emit (/mnt/ebs/deploy/SCCluster/socketcluster/sample/node_modules/sc-domain/index.js:12:31)
  name: 'SocketProtocolError',
  message: 'Socket hung up',
  code: 1006 }
`

Individual connections from browser still succeed but I see that the channel information is not getting shared between multiple instances of the app running on different ports. So, I suspect the socketcluster apps are unable to communicate with broker instance. 

Note: The guide says we need to run the server.js file in socketcluster root directory but since I don't find one there, I am running the one I find in socketcluster/sample directory after running "npm install" in that directory.

Versions : All latest repos from master branch
System : Ubuntu 14.04

Kindly let me know if I am doing anything wrong.

**Comment by nagamanojv** [comment]
Okay, this turned out to be because socket.remoteAddress is coming as 'undefined' in sc-state/server.js on serverJoinCluster and clientJoinCluster. Because of this socketcluster was given undefined as the port to connect which it obviously couldn't. When I hardcoded socket.instanceIp = '127.0.0.1';  in both serverJoinCluster and clientJoinCluster everything is working perfectly. 

Now, can anyone help me how can I overcome this limitation.!! For sc-broker, I can set SCC_INSTANCE_IP env variable to inform state server about the source ip, but for socketcluster I don't see any corresponding variable being used.

**Comment by jondubois** [comment]
@nagamanojv What node.js version are you using?

**Comment by nagamanojv** [comment]
@jondubois  it is  node v7.4.0

**Comment by jondubois** [comment]
@nagamanojv When I connect to a socketcluster server from a socketcluster-client running inside Node.js (v7.10.0), on the server `socket.remoteAddress` is `::ffff:127.0.0.1` which is fine.

It would be interesting to know why it says undefined in your case.

I just used this code as the client and I run this with the `node` command:

```
var socketCluster = require('socketcluster-client');

var socket = socketCluster.connect({
  hostname: 'localhost',
  port: 8000
});

socket.on('connect', function () {
  console.log('CONNECT', arguments);
});
```

**Comment by joyson-17** [comment]
I faced the same issue and I did a small workaround in index.js of the sc-cluster-broker-client module. Not sure if this is the right way to go about it:

```
var SCC_INSTANCE_IP = process.env.SCC_INSTANCE_IP;
var SCC_INSTANCE_IP_FAMILY = process.env.SCC_INSTANCE_IP_FAMILY || `'IPv4';`

  var stateSocketData = {
    instanceId: broker.instanceId,
    instanceIp: SCC_INSTANCE_IP,
    instanceIpFamily: SCC_INSTANCE_IP_FAMILY
  };
```

In the socketcluster yaml file, added the following in the environment variable:
        - name: SCC_INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

**Comment by nagamanojv** [comment]
@jondubois the piece of code you gave is giving ::ffff:127.0.0.1 as socket.remoteAddress for me also. It is surprising why it is not giving the same value when socket-state tries to read.!!

**Comment by jondubois** [comment]
@nagamanojv @joyson-17 There was an issue which mean that remoteAddress was not being set sometimes when using `uws` as the engine. I fixed this in socketcluster `v5.11.0`.

**Comment by joysonvd** [comment]
Tried this with socketcluster 5.16 and still getting undefined.

Client e7fda3ab-4e72-4489-b319-e6ee2d07a827 at address undefined joined the cluster
Cluster state converged to active:[]

Server 00eaadd0-3569-4fc2-87f1-57abe06bbf05 at address undefined on port 8888 joined the cluster
Cluster state converged to updatedSubs:["ws://[undefined]:8888"]
Cluster state converged to updatedPubs:["ws://[undefined]:8888"]
Cluster state converged to active:["ws://[undefined]:8888"]

**Comment by joysonvd** [comment]
Hi,

Please close this. I was not using the correct version on the state server.

Thanks

**Comment by lecoleco** [comment]
Hi, i try to use scc in minikube and get that.

Error [SocketProtocolError]: Socket hung up
    at AGClientSocket._destroy (/usr/src/node_modules/socketcluster-client/lib/clientsocket.js:678:15)
    at AGTransport.onOpenAbort (/usr/src/node_modules/socketcluster-client/lib/clientsocket.js:366:16)
    at AGTransport._destroy (/usr/src/node_modules/socketcluster-client/lib/transport.js:254:10)
    at WebSocket.AGTransport.wsSocket.onerror (/usr/src/node_modules/socketcluster-client/lib/transport.js:92:12)
    at WebSocket.onError (/usr/src/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:223:5)
    at ClientRequest.<anonymous> (/usr/src/node_modules/ws/lib/websocket.js:554:15)
    at ClientRequest.emit (events.js:223:5)
    at Socket.socketErrorListener (_http_client.js:415:9)
    at Socket.emit (events.js:223:5) {
  name: 'SocketProtocolError',
  message: 'Socket hung up',
  code: 1006
}
